// 마레·생폴 일대 손으로 쓴 장소들 (2차). places.ts의 CURATED와 content.ts가 함께 읽는다.
// 규칙: 사진은 위키미디어 공용 파일명('file:…'), 없으면 생략. 가격·시간은 대략값. 확실치 않은 것은 쓰지 않는다.
import type { Cat } from './places';
import type { Dish, Moment, Tag } from './content';

export interface Rich {
  match: RegExp;
  name: string;
  cat: Cat;
  emoji: string;
  blurb: string;
  mins?: number;
  cost?: number;
  photos?: string[];
  moments?: Moment[];
  dishes?: Dish[];
  menuNote?: string;
  pos?: [number, number]; // OSM에 없을 때만
}

const F = (n: string) => `file:${n}`;
const D = (name: string, fr: string, desc: string, price: number, mins: number, emoji: string, tags: Tag[], photo?: string[]): Dish => ({ name, fr, desc, price, mins, emoji, tags, photo });

export const RICH: Rich[] = [
  // ───────── 큰 볼거리 ─────────
  { match: /^Église Saint-Gervais$/i, name: '생제르베 성당', cat: 'sight', emoji: '⛪', mins: 15, photos: [F('Church of St-Gervais-et-St-Protais Interior 1, Paris, France - Diliff.jpg')],
    blurb: '시청 뒤편, 파리에서 가장 오래된 느릅나무가 서 있던 자리 앞의 성당. 고딕 몸통에 17세기 초 고전주의 정면을 붙였다. 쿠프랭 집안이 두 세기 동안 오르간을 쳤다.',
    moments: [
      { text: '느릅나무 광장 쪽에서 올려다보면 세 층으로 쌓인 기둥 정면. 파리에서 이런 정면은 이게 처음이었다.', mins: 3, photo: [F('Paris, Saint-Gervais-Saint-Protais, Innenansicht (13).jpg')] },
      { text: '안은 뜻밖에 높고 어둡다. 촛불과 수도 공동체의 낮은 노래 소리.', mins: 7, photo: [F('Church of St-Gervais-et-St-Protais Interior 2, Paris, France - Diliff.jpg')] },
      { text: '뒤편 오르간 아래. 쿠프랭이 앉았던 자리라는 안내판.', mins: 5, photo: [F('Paris, Saint-Gervais-Saint-Protais, Positiv (4).jpg')] },
    ] },
  { match: /^Hôtel de Ville$/i, name: '파리 시청 Hôtel de Ville', cat: 'sight', emoji: '🏛️', mins: 10, photos: [F('Paris, Hôtel de Ville -- 2014 -- 1714.jpg')],
    blurb: '1871년 코뮌 때 불탄 뒤 옛 모습대로 다시 지은 시청. 정면의 조각상 100여 개는 전부 파리 출신 인물이다. 앞 광장은 겨울엔 스케이트장이 된다.',
    moments: [
      { text: '광장 한복판에 서면 정면이 한눈에 안 들어온다. 창마다 사람 조각이 하나씩.', mins: 4, photo: [F('Paris, Hôtel de Ville -- 2014 -- 1720-5 - 2.jpg')] },
      { text: '가까이 가면 돌마다 이름이 새겨져 있다. 볼테르, 몰리에르… 전부 파리 사람.', mins: 4, photo: [F('Hôtel de Ville de Paris détail façade.jpg')] },
    ] },
  { match: /^Hôtel de Soubise$/i, name: '오텔 드 수비즈 · 국립기록보관소', cat: 'sight', emoji: '🏰', mins: 15, photos: [F('Hotel de Soubise cour d\'honneur 1.JPG')],
    blurb: '반원형 열주가 둘러싼 명예의 안뜰이 프랑스 국립기록보관소의 얼굴. 안에는 로코코 장식이 가장 잘 남은 방들이 있다(기록보관소 박물관).',
    moments: [
      { text: '큰 문을 지나면 갑자기 열리는 반원형 안뜰. 기둥이 56개라던가.', mins: 5, photo: [F('P1300267 Paris III hotel de Soubise cour rwk.jpg')] },
      { text: '뒤편 정원으로 돌아간다. 담장 너머 저택 지붕들이 이어진다.', mins: 6, photo: [F('Garden of the Hôtel de Soubise.jpg')] },
    ] },
  { match: /^Jardin des Archives-Nationales$/i, name: '국립기록보관소 정원', cat: 'park', emoji: '🌳', mins: 12, photos: [F('Garden @ Archives nationales @ Le Marais @ Paris (33693754424).jpg')],
    blurb: '저택 네 채 사이에 숨은 정원. 마레에서 가장 조용한 잔디밭 중 하나. 무료, 낮에만 연다.',
    moments: [
      { text: '좁은 골목 같은 통로로 들어간다. 소음이 뚝 끊긴다.', mins: 3, photo: [F('Ruelle de la Roche, Archives nationales, Paris 8 May 2017.jpg')] },
      { text: '잔디에 앉는다. 담장 너머로 오텔 드 로앙의 지붕.', mins: 9, photo: [F('Garden @ Archives nationales @ Le Marais @ Paris (34375462522).jpg')] },
    ] },
  { match: /^Musée des Archives nationales$/i, name: '기록보관소 박물관', cat: 'museum', emoji: '📜', mins: 45, cost: 0,
    blurb: '오텔 드 수비즈 안, 로코코 살롱들을 지나며 루이 16세의 일기부터 잔 다르크 재판 기록까지 나라의 원본 문서를 본다. 상설 전시는 무료.',
    moments: [
      { text: '공주의 살롱. 타원형 방에 금박과 거울, 천장까지 온통 곡선.', mins: 15, photo: [F('Gate @ Musée des Archives nationales - Hôtel de Soubise @ Le Marais @ Paris (35031258652).jpg')] },
      { text: '유리장 속 문서 한 장 앞에서 오래 선다. 글씨가 사람이었다는 게 실감난다.', mins: 20 },
      { text: '안뜰로 나오니 햇빛이 눈부시다.', mins: 5 },
    ] },
  { match: /^Hôtel de Rohan/i, name: '오텔 드 로앙', cat: 'sight', emoji: '🏰', mins: 8, photos: [F('Hôtel de Rohan 2017.jpg')],
    blurb: '수비즈 옆 저택. 마구간 위에 새겨진 「아폴론의 말들」 부조가 유명하다. 정원 쪽에서 보는 뒷면이 더 좋다.',
    moments: [
      { text: '안뜰 구석, 물 마시는 말들의 부조. 돌이 아니라 물결 같다.', mins: 4, photo: [F('Hôtel de Rohan Paris 3e 001.JPG')] },
      { text: '정원 쪽으로 돌아가 뒷면을 본다.', mins: 4, photo: [F('Hôtel de Rohan, Paris - View from Garden.jpg')] },
    ] },
  { match: /chasse et de la nature/i, name: '사냥과 자연 박물관', cat: 'museum', emoji: '🦌', mins: 70, cost: 12, photos: [F('Musée de la Chasse et de la Nature Paris Aug 2026 03.jpg')],
    blurb: '17세기 저택 두 채에 박제와 그림, 현대미술을 섞어 놓은 기묘하고 아름다운 박물관. 부엉이 천장의 방이 있다.',
    moments: [
      { text: '멧돼지, 사슴, 곰. 박제인데 방마다 성격이 다르다.', mins: 20, photo: [F('Musée de la Chasse et de la Nature Paris Aug 2026 13.jpg')] },
      { text: '작은 방 천장이 온통 부엉이 깃털이다. 고개를 젖히고 한참.', mins: 15, photo: [F('Musée de la Chasse et de la Nature Paris Aug 2026 11.jpg')] },
      { text: '유니콘의 방을 지나 계단으로. 여긴 박물관보다 누군가의 집 같다.', mins: 25, photo: [F('Musée de la Chasse et de la Nature Paris Aug 2026 02.jpg')] },
    ] },
  { match: /Judaïsme/i, name: '유대 예술·역사 박물관', cat: 'museum', emoji: '🕎', mins: 80, cost: 10, photos: [F('Paris - Hôtel de Saint-Aignan - Museé du Judaïsme.jpg')],
    blurb: '오텔 드 생테냥에 자리한 박물관. 중세부터 현대까지 유럽과 북아프리카 유대인의 삶을 물건과 그림으로 따라간다. 샤갈, 모딜리아니, 수틴.',
    moments: [
      { text: '안뜰의 기둥머리부터 17세기. 큰 계단을 오른다.', mins: 8, photo: [F('L\'Hôtel de Saint-Aignan, le grand escalier - Musée d\'Art et d\'Histoire du Judaïsme.jpg')] },
      { text: '결혼 계약서, 하누카 촛대, 토라 장식. 가족 물건들.', mins: 35 },
      { text: '20세기 방. 이 건물에 살던 사람들의 이름이 안뜰에 적혀 있다.', mins: 30, photo: [F('Paris Hôtel de Saint-Aignan Chapiteau 2013.jpg')] },
    ] },
  { match: /^Centre Georges Pompidou$/i, name: '퐁피두 센터', cat: 'museum', emoji: '🎨', mins: 90, cost: 15, photos: [F('View from the Centre Pompidou 2.jpg')],
    blurb: '배관을 밖으로 꺼낸 건물. 에스컬레이터 튜브를 타고 오르는 것만으로 파리 지붕이 펼쳐진다. 2025년부터 대규모 개보수로 장기 휴관 중이니 가기 전에 꼭 확인.',
    moments: [
      { text: '광장에 앉아 건물을 본다. 파랑은 공조, 초록은 물, 노랑은 전기, 빨강은 사람.', mins: 10, photo: [F('Air Vents at the Centre Pompidou 2.jpg')] },
      { text: '유리 튜브 에스컬레이터. 한 층 오를 때마다 지붕이 더 멀리 보인다.', mins: 15, photo: [F('View from the Centre Pompidou.jpg')] },
      { text: '꼭대기에서 몽마르트르까지.', mins: 15, photo: [F('Interior of the Centre Pompidou 2.jpg')] },
    ] },
  { match: /^Opéra Bastille$/i, name: '오페라 바스티유', cat: 'sight', emoji: '🎭', mins: 8, photos: [F('Side View of the Opéra Bastille.jpg')],
    blurb: '혁명 200주년(1989)에 문을 연 현대식 오페라 극장. 광장 한가운데 7월 기둥과 마주 서 있다. 낮에는 유리 계단만 봐도 된다.',
    moments: [
      { text: '광장 한가운데, 초록 천사가 올라앉은 7월 기둥. 1830년 혁명의 희생자들이 그 아래 묻혀 있다.', mins: 4, photo: [F('Colonne de Juillet, Place de la Bastille, Paris.jpg')] },
      { text: '오페라의 넓은 계단에 앉아 광장을 본다. 감옥 자리는 지금 도로 밑.', mins: 4, photo: [F('Opéra Bastille GJ.jpg')] },
    ] },
  { match: /^Ruines de la Bastille$/i, name: '바스티유 감옥 터', cat: 'sight', emoji: '🧱', mins: 5, photos: [F('Bastille - colonne de juillet 2384.JPG')],
    blurb: '감옥은 1789년 헐려 돌 하나 남지 않았다. 광장 바닥의 선과 지하철 5호선 승강장 벽의 돌무더기가 흔적의 전부. 광장 바닥에 그려진 윤곽선을 찾아보자.',
    moments: [
      { text: '바닥의 돌 선을 따라 걷는다. 이게 성벽 자리.', mins: 5 },
    ] },
  { match: /^Musée de la Magie$/i, name: '마술 박물관', cat: 'museum', emoji: '🎩', mins: 60, cost: 14,
    blurb: '생폴 거리의 지하 저장고에 꾸민 마술 박물관. 19세기 자동인형과 착시 상자, 그리고 짧은 마술 공연이 입장에 포함된다. 아이가 있으면 여기.',
    moments: [
      { text: '둥근 천장의 지하로 내려간다. 거울 방, 커지는 손, 수수께끼 상자.', mins: 20 },
      { text: '작은 무대에서 마술사가 카드를 편다. 어른도 속는다.', mins: 25 },
      { text: '자동인형 방. 태엽을 감으면 눈을 깜빡인다.', mins: 15 },
    ] },
  { match: /^Maison européenne de la Photographie$/i, name: '유럽 사진의 집 MEP', cat: 'museum', emoji: '📷', mins: 60, cost: 10, photos: [F('Maison Européenne de la Photographie (Paris), façade 2.JPG')],
    blurb: '18세기 저택을 통째로 사진 전시장으로 쓴다. 상설 전시가 없고 기획전만 돌기 때문에 갈 때마다 다르다. 지하의 도서관과 카페까지 볼 것.',
    moments: [
      { text: '흰 벽, 나무 바닥, 사진 한 장 앞에 의자 하나.', mins: 25 },
      { text: '계단참에서 안뜰이 내려다보인다.', mins: 5, photo: [F('P1080197 Paris IV maison européenne de la photographie rwk.JPG')] },
      { text: '지하 도서관. 사진집을 한 권 꺼내 앉는다.', mins: 20 },
    ] },
  { match: /^Hôtel de Chavigny$/i, name: '오텔 드 샤비니 · 샤를마뉴 고등학교', cat: 'sight', emoji: '🏫', mins: 5,
    blurb: '생폴 생루이 성당 옆, 옛 예수회 수도원이 지금은 고등학교. 안은 못 들어가지만 골목 쪽 담장 위로 옛 지붕과 시계가 보인다.',
    moments: [
      { text: '담장 너머로 종탑과 시계. 쉬는 시간이면 안뜰에서 웃음소리가 넘어온다.', mins: 5 },
    ] },
  { match: /^Synagogue$/i, name: '파베 거리 시나고그 (기마르)', cat: 'sight', emoji: '🕍', mins: 6, photos: [F('Paris Synagogue Guimard, rue pavée398.JPG')],
    blurb: '지하철 입구를 디자인한 엑토르 기마르가 지은 유일한 종교 건물(1913). 좁은 정면이 물결처럼 휜다. 평소엔 안에 못 들어가고, 정면만으로 충분하다.',
    moments: [
      { text: '좁은 골목이라 뒤로 물러설 수가 없다. 고개를 젖혀 물결치는 정면을 본다.', mins: 4, photo: [F('Guimard-4eme-artnouveau-10-rue-pavee-synagogue.jpg')] },
      { text: '문 옆 돌에 기마르의 서명.', mins: 2, photo: [F('Guimard-4eme-artnouveau-10-rue-pavee-synagogue-signature.jpg')] },
    ] },
  { match: /^Temple du Marais$/i, name: '마레 개신교회 (옛 생트마리 성당)', cat: 'sight', emoji: '⛪', mins: 8, photos: [F('Paris 75004 Temple du Marais (temple Sainte-Marie) 20151213.jpg')],
    blurb: '베르사유를 짓기 전의 프랑수아 망사르가 설계한 둥근 성당(1634). 생탕투안 거리에서 돔이 불쑥 보인다. 지금은 개신교회.',
    moments: [
      { text: '큰길에서 돔부터 눈에 들어온다. 안은 완전한 원형.', mins: 5, photo: [F('Temple Sainte-Marie du Marais à Paris 75004.jpg')] },
      { text: '문이 열려 있으면 들어가 천장을 올려다본다.', mins: 3 },
    ] },
  { match: /^Square Georges-Cain$/i, name: '조르주 캥 광장', cat: 'park', emoji: '🌿', mins: 12, photos: [F('Square Georges-Cain 01 tonemapped.jpg')],
    blurb: '카르나발레 뒤편의 작은 정원. 파리 곳곳에서 헐린 건물의 조각 파편들이 담장을 따라 놓여 있다. 야외 창고 같은 정원.',
    moments: [
      { text: '담장 아래 돌 조각들. 튈르리 궁의 잔해라는 안내판.', mins: 5, photo: [F('Paris 3e Square Georges-Cain 461.jpg')] },
      { text: '가운데 벤치. 동네 사람들의 점심 도시락.', mins: 7, photo: [F('Square George Cain @ Paris (31001146521).jpg')] },
    ] },
  { match: /^Square Léopold Achille$/i, name: '레오폴 아실 광장', cat: 'park', emoji: '🌳', mins: 10, photos: [F('Square Léopold-Achille @ Le Marais @ Paris (33570705594).jpg')],
    blurb: '조르주 캥 옆, 놀이터와 잔디가 있는 동네 공원. 카르나발레 관람 뒤 앉아 쉬기 좋다.',
    moments: [
      { text: '잔디 가장자리에 앉는다. 담장 너머로 옛 저택의 뒷면.', mins: 10, photo: [F('Hôtel Duret de Chevry, Square Léopold-Achille, Paris 2 May 2017.jpg')] },
    ] },
  { match: /^Jardin Anne Frank$/i, name: '안네 프랑크 정원', cat: 'park', emoji: '🌳', mins: 12, photos: [F('Jardin Anne Frank, Le Marais, Paris 2017 001.jpg')],
    blurb: '건물들 사이 통로 끝에 숨어 있어 지나치기 쉬운 정원. 암스테르담의 안네 프랑크 집 앞 밤나무에서 가져온 나무가 자란다.',
    moments: [
      { text: '통로를 끝까지 걸어야 나온다. 체스 테이블과 밤나무.', mins: 6, photo: [F('Chess tables, Jardin Anne Frank, Paris 11 November 2016.jpg')] },
      { text: '안쪽 정원은 담장으로 둘러싸여 완전히 조용하다.', mins: 6, photo: [F('Jardin Anne Frank @ Beaubourg @ Paris (30886079296).jpg')] },
    ] },
  { match: /^Square Marie Trintignant$/i, name: '마리 트랭티냥 광장', cat: 'park', emoji: '🌉', mins: 10, photos: [F('Square Marie Trintignant @ Paris (32579387682).jpg')],
    blurb: '오텔 드 상스 뒤편, 센 강과 생루이 섬이 내려다보이는 작은 공원. 마레에서 강을 보는 가장 가까운 자리.',
    moments: [
      { text: '난간에 기대면 생루이 섬의 지붕들과 퐁 마리.', mins: 6, photo: [F('P1030890 Paris IV square Marie-Trintignant rwk.JPG')] },
      { text: '강바람. 유람선 한 척.', mins: 4, photo: [F('Square Marie Trintignant @ Paris (31889753484).jpg')] },
    ] },
  { match: /^Jardin Lazare-Rachline$/i, name: '라자르 라슐린 정원', cat: 'park', emoji: '🌿', mins: 10, photos: [F('Jardin Lazare-Rachline, Paris 9 June 2017 001.jpg')],
    blurb: '스웨덴 문화원(오텔 드 마를) 옆, 파옌 거리의 작은 정원. 문화원 카페의 시나몬 롤을 들고 앉기 좋다.',
    moments: [
      { text: '철문 안쪽 잔디. 옆 건물 카페에서 커피 냄새.', mins: 10, photo: [F('Paris 3e Rue Payenne 9 Jardin Lazare-Rachline 715.jpg')] },
    ] },
  { match: /^Hôtel de Marle$/i, name: '오텔 드 마를 · 스웨덴 문화원', cat: 'cafe', emoji: '🇸🇪', mins: 30, cost: 8, photos: [F('Hôtel de Marle.jpg')],
    blurb: '16세기 저택에 든 스웨덴 문화원. 안뜰의 카페 쉬에두아(Café Suédois)가 마레의 숨은 점심 자리다. 시나몬 롤과 오픈 샌드위치.',
    dishes: [
      D('시나몬 롤', 'Kanelbulle', '스웨덴식 계피 빵. 커피와.', 4, 15, '🌀', ['sweet', 'classic']),
      D('오픈 샌드위치', 'Smörgås', '호밀빵에 연어 또는 달걀.', 9, 25, '🥪', ['savory', 'classic']),
      D('커피', 'Kaffe', '스웨덴 사람들은 하루 몇 잔이라던가.', 3, 10, '☕', ['drink']),
    ], menuNote: '안뜰 카페의 대표 메뉴. 가격은 대략입니다.' },
  { match: /^Square Louis-XIII$/i, name: '루이 13세 광장 (보주 광장 안)', cat: 'park', emoji: '⛲', mins: 15, photos: [F('Square Louis-XIII (10054623153).jpg')],
    blurb: '보주 광장 한가운데의 정원. 네 귀퉁이 분수와 가운데 루이 13세 기마상. 잔디에 앉아도 된다.',
    moments: [
      { text: '분수 옆 벤치. 사방이 똑같은 창문이라 방향을 잃는다.', mins: 8, photo: [F('Square Louis XIII @ Place des Vosges @ Marais @ Paris (30865194294).jpg')] },
      { text: '기마상 아래 그늘.', mins: 7, photo: [F('F0720 Paris IV square Louis XIII rwk.jpg')] },
    ] },
  { match: /^Fontaine de Jarente$/i, name: '자랑트 분수', cat: 'sight', emoji: '⛲', mins: 3, photos: [F('Fontaine de Jarente.jpg')],
    blurb: '막다른 골목 끝에 붙어 있는 1783년의 작은 분수. 알고 찾아가지 않으면 못 본다.',
    moments: [{ text: '골목 끝 벽의 돌 분수. 물은 안 나온다.', mins: 3, photo: [F('Fontaine de Jarente détail.jpg')] }] },
  { match: /^Bibliothèque Forney$/i, name: '포르네 도서관 (오텔 드 상스)', cat: 'sight', emoji: '📚', mins: 8, photos: [F('Hotel de Sens.jpg')],
    blurb: '오텔 드 상스 안의 장식미술·포스터 전문 도서관. 회원이 아니어도 로비와 전시실은 들어갈 수 있다. 중세 저택 안을 걸어 보는 핑계.',
    moments: [{ text: '뾰족한 문을 지나 안으로. 나선 계단 옆에 옛 포스터 전시.', mins: 8, photo: [F('Plaque bibliothèque Forney hôtel de Sens.jpg')] }] },
  { match: /^Jardin Roger Priou-Valjean$/i, name: '로제 프리우발장 정원', cat: 'park', emoji: '🌿', mins: 8, photos: [F('Jardin Roger-Priou-Valjean @ Paris (31889733244).jpg')],
    blurb: '필리프 오귀스트 성벽 아래 붙은 좁고 긴 정원. 800년 된 벽을 등지고 앉는다.',
    moments: [{ text: '성벽에 등을 기대고 앉는다. 돌이 따뜻하다.', mins: 8, photo: [F('P1320566 Paris IV jardin Roger-Priou-Valjean rwk.jpg')] }] },
  { match: /^Hôtel de Chaulnes$/i, name: '오텔 드 숄른', cat: 'sight', emoji: '🏰', mins: 4, photos: [F('Paris 4e Place des Vosges Hôtel de Chaulnes 567.jpg')],
    blurb: '보주 광장 9번지. 지금은 건축 아카데미. 문이 열려 있으면 안뜰까지는 들여다볼 수 있다.',
    moments: [{ text: '아케이드 아래 큰 문. 틈으로 안뜰과 해시계.', mins: 4, photo: [F('Petit hôtel de Sully. L\'entrée par les cours du 9 place des Vosges. Cadran solaire de l\'hôtel sur le jardinet. G.11592.jpg')] }] },
  { match: /^Hôtel de la Salle$/i, name: '오텔 드 라 살', cat: 'sight', emoji: '🏰', mins: 3, photos: [F('Paris 4e Place des Vosges Hôtel de la Salle 565.jpg')],
    blurb: '보주 광장의 저택 중 하나. 광장의 36채는 겉모습이 같아야 한다는 규칙으로 지어졌다.',
    moments: [{ text: '똑같은 붉은 벽돌 정면. 문패로만 구별된다.', mins: 3 }] },
  { match: /^Maison dite « de Jacques Cœur »$/i, name: '자크 쾨르의 집', cat: 'sight', emoji: '🏚️', mins: 4, photos: [F('Ancienne maison de Jacques Coeur.JPG')],
    blurb: '15세기 대상인 자크 쾨르의 것이라 전해지는 벽돌 집. 파리에 몇 안 남은 중세 벽돌 건물.',
    moments: [{ text: '붉은 벽돌과 돌을 번갈아 쌓은 정면. 이 동네에서 제일 오래된 벽.', mins: 4, photo: [F('Plaque Jacques Coeur.JPG')] }] },
  { match: /^Rue des Rosiers$/i, name: '로지에 거리', cat: 'sight', emoji: '🥯', mins: 10, photos: [F('Rue des Rosiers, Paris, France 01.jpg')],
    blurb: '마레의 옛 유대인 거리. 팔라펠 줄, 노란 빵집, 그리고 요즘은 옷가게. 일요일에 제일 붐빈다.',
    moments: [
      { text: '팔라펠 냄새와 줄. 골목이 좁아 어깨가 부딪힌다.', mins: 5, photo: [F('Rue des Rosiers 4, Paris September 23, 2012.jpg')] },
      { text: '노란 간판, 히브리어 간판, 그 사이의 명품 매장.', mins: 5, photo: [F('Rue des Rosiers, Paris 2011.jpg')] },
    ] },

  // ───────── 먹는 곳 ─────────
  { match: /^Le Loir dans la Théière$/i, name: '르 루아르 당 라 테이에르', cat: 'cafe', emoji: '🥧', mins: 40, cost: 12,
    blurb: '"찻주전자 속의 겨울잠쥐". 낡은 소파와 벽보로 가득한 살롱 드 테. 머랭이 산처럼 쌓인 레몬 타르트로 유명하다. 주말 브런치는 줄이 길다.',
    dishes: [
      D('레몬 머랭 타르트', 'Tarte au citron meringuée', '머랭이 10cm는 된다. 이 집의 그것.', 9, 25, '🍋', ['sweet', 'classic']),
      D('오늘의 타르트(짠맛)', 'Tarte salée du jour', '샐러드가 곁들여진다.', 14, 35, '🥧', ['savory']),
      D('차 한 주전자', 'Théière', '이름값. 큰 주전자로 나온다.', 6, 20, '🫖', ['drink', 'classic']),
      D('쇼콜라 쇼', 'Chocolat chaud', '', 6, 20, '☕', ['drink', 'sweet']),
    ], menuNote: '이 집에서 유명한 것들. 가격은 대략입니다.' },
  { match: /^Breakfast in America/i, name: '브렉퍼스트 인 아메리카', cat: 'eat', emoji: '🥞', mins: 40, cost: 16,
    blurb: '파리 한복판의 미국식 다이너. 빨간 부스, 끝없이 채워주는 커피, 팬케이크. 프랑스식 아침에 지쳤을 때.',
    dishes: [
      D('팬케이크 한 접시', 'Pancakes', '메이플 시럽과 버터.', 10, 30, '🥞', ['sweet', 'classic']),
      D('치즈버거와 감자튀김', 'Cheeseburger', '', 15, 35, '🍔', ['savory', 'classic']),
      D('밀크셰이크', 'Milkshake', '바닐라·초코·딸기.', 7, 15, '🥤', ['sweet', 'drink']),
      D('필터 커피', 'Coffee', '리필 무료.', 3, 10, '☕', ['drink']),
    ], menuNote: '다이너의 기본 메뉴. 가격은 대략입니다.' },
  { match: /^Laurent Dubois$/i, name: '로랑 뒤부아 (치즈)', cat: 'gourmet', emoji: '🧀', mins: 12, cost: 0,
    blurb: '프랑스 최우수 장인(MOF) 치즈 숙성사의 가게. 냄새가 문 밖까지 난다. 조금씩 잘라 팔아 주니 호텔에서 먹을 치즈 세 조각을 고르기 좋다.',
    dishes: [
      D('콩테 24개월', 'Comté 24 mois', '결정이 씹힌다.', 6, 5, '🧀', ['savory', 'classic']),
      D('생마르슬랭', 'Saint-Marcellin', '숟가락으로 떠먹는 부드러운 치즈.', 4, 5, '🥄', ['savory', 'classic']),
      D('염소 치즈 하나', 'Chèvre', '오늘 제일 좋은 걸 물어본다.', 5, 5, '🐐', ['savory', 'classic']),
      D('구경만 한다', '', '냄새만 맡아도 된다.', 0, 8, '👃', []),
    ], menuNote: '100g 안팎 기준 대략 가격.' },
  { match: /^Maison Georges Larnicol$/i, name: '메종 조르주 라르니콜', cat: 'sweet', emoji: '🧈', mins: 8, cost: 4,
    blurb: '브르타뉴 출신 쇼콜라티에. 한 입 크기 퀴녜트(작은 퀴니아망)를 무게로 판다. 버터와 설탕이 캐러멜로 굳은 것.',
    dishes: [
      D('퀴녜트 한 봉지', 'Kouignettes', '여러 맛 섞어서. 종이봉투에 담아 준다.', 6, 5, '🧈', ['sweet', 'classic', 'street']),
      D('마카롱', 'Macarons', '', 2, 3, '🧁', ['sweet']),
      D('초콜릿 한 조각', 'Chocolat', '', 3, 3, '🍫', ['sweet']),
    ], menuNote: '무게로 파는 집. 가격은 대략입니다.' },
  { match: /^Yann Couvreur/i, name: '얀 쿠브뢰르 파티스리', cat: 'sweet', emoji: '🦊', mins: 10, cost: 8,
    blurb: '여우 로고의 파티스리. 팔레스 호텔 셰프 출신. 주문하면 그 자리에서 층을 쌓아 주는 밀푀유가 이 집의 얼굴.',
    dishes: [
      D('밀푀유', 'Millefeuille minute', '주문하면 바로 쌓는다. 바삭함이 다르다.', 9, 10, '🍰', ['sweet', 'trendy']),
      D('오늘의 타르트', 'Tarte', '', 8, 8, '🥧', ['sweet', 'trendy']),
      D('바닐라 플랑', 'Flan', '', 6, 6, '🍮', ['sweet', 'classic']),
    ], menuNote: '대표 메뉴. 가격은 대략입니다.' },
  { match: /^Copains Rosiers$/i, name: '코팽 (빵집)', cat: 'bakery', emoji: '🥖', mins: 6, cost: 3,
    blurb: '로지에 거리 초입의 유기농 빵집. 통밀과 천연 발효.',
    dishes: [
      D('통밀 바게트', 'Baguette', '', 2, 3, '🥖', ['savory', 'classic', 'street']),
      D('크루아상', 'Croissant', '', 2, 4, '🥐', ['sweet', 'classic', 'street']),
      D('샌드위치', 'Sandwich', '', 7, 12, '🥪', ['savory', 'street']),
    ] },
  { match: /^Ma Bourgogne$/i, name: '마 부르고뉴', cat: 'eat', emoji: '🥩', mins: 60, cost: 30,
    blurb: '보주 광장 아케이드 아래의 오래된 브라스리. 테라스에서 광장을 보며 먹는 타르타르와 부르고뉴 와인. 현금만 받는 것으로 유명했다.',
    dishes: [
      D('스테이크 타르타르', 'Tartare de bœuf', '테이블 옆에서 섞어 준다. 감자튀김과.', 26, 50, '🥩', ['savory', 'classic']),
      D('뵈프 부르기뇽', 'Bœuf bourguignon', '이름이 부르고뉴다.', 24, 50, '🍲', ['savory', 'classic']),
      D('양파 수프', "Soupe à l'oignon", '', 12, 20, '🥣', ['savory', 'classic']),
      D('부르고뉴 한 잔', 'Verre de Bourgogne', '', 8, 15, '🍷', ['drink', 'alcohol', 'classic']),
    ], menuNote: '대표 메뉴. 가격은 대략입니다.' },
  { match: /^Café Hugo$/i, name: '카페 위고', cat: 'cafe', emoji: '☕', mins: 30, cost: 8,
    blurb: '보주 광장 아케이드의 카페. 자리값이 붙지만 광장을 보며 앉아 있는 값이다.',
    dishes: [
      D('카페 크렘', 'Café crème', '', 5, 20, '☕', ['drink', 'classic']),
      D('크로크무슈', 'Croque-monsieur', '', 13, 25, '🥪', ['savory', 'classic']),
      D('와인 한 잔', 'Verre de vin', '', 7, 25, '🍷', ['drink', 'alcohol']),
    ] },
  { match: /^Chez Janou$/i, name: '셰 자누', cat: 'eat', emoji: '🍲', mins: 70, cost: 30,
    blurb: '프로방스 음식의 비스트로. 큰 사발째 내와서 덜어 먹게 하는 초콜릿 무스가 전설이다. 저녁엔 예약 없이는 어렵다.',
    dishes: [
      D('오늘의 프로방스 요리', 'Plat du jour', '라타투이나 도브(소고기 찜) 같은 것.', 22, 45, '🍲', ['savory', 'classic']),
      D('초콜릿 무스 (사발째)', 'Mousse au chocolat', '큰 사발이 오면 알아서 덜어 먹는다.', 9, 15, '🍫', ['sweet', 'classic']),
      D('파스티스', 'Pastis', '80종이 넘는다던가.', 6, 10, '🥃', ['drink', 'alcohol', 'classic']),
    ], menuNote: '대표 메뉴. 가격은 대략입니다.' },
  { match: /^Brasserie Bofinger$/i, name: '브라스리 보팽제', cat: 'eat', emoji: '🦪', mins: 80, cost: 40,
    blurb: '1864년 문을 연 파리에서 가장 오래된 브라스리 중 하나. 스테인드글라스 돔 아래서 굴과 슈크루트. 돔 아래 자리를 달라고 하자.',
    dishes: [
      D('슈크루트', 'Choucroute', '알자스식 양배추 절임에 소시지와 돼지고기.', 30, 60, '🍖', ['savory', 'classic']),
      D('굴 반 다스', 'Huîtres', '', 20, 25, '🦪', ['savory', 'classic']),
      D('생맥주', 'Bière pression', '알자스 맥주.', 7, 15, '🍺', ['drink', 'alcohol', 'classic']),
      D('일 플로탕트', 'Île flottante', '커스터드 위에 떠 있는 머랭.', 10, 15, '🍮', ['sweet', 'classic']),
    ], menuNote: '대표 메뉴. 가격은 대략입니다.',
    photos: [F('Brasserie Bofinger.JPG')],
    moments: [{ text: '돔 아래 자리. 유리 천장으로 빛이 내려온다.', mins: 5, photo: [F('Brasserie Bofinger (16083013427).jpg')] }] },
  { match: /^Café des Musées$/i, name: '카페 데 뮈제', cat: 'eat', emoji: '🍽️', mins: 60, cost: 28, photos: [F('"Café des Musées", rue de Turenne (36566334433).jpg')],
    blurb: '튀렌 거리 모퉁이의 동네 비스트로. 칠판 메뉴, 스테이크 프리트, 수플레. 카르나발레·피카소 사이에서 점심.',
    dishes: [
      D('스테이크 프리트', 'Entrecôte frites', '', 26, 45, '🥩', ['savory', 'classic']),
      D('오늘의 요리', 'Plat du jour', '칠판에.', 18, 40, '🍲', ['savory', 'classic']),
      D('수플레', 'Soufflé', '주문하면 20분 걸린다.', 11, 25, '🍮', ['sweet', 'classic']),
    ], menuNote: '대표 메뉴. 가격은 대략입니다.' },
  { match: /^Robert et Louise$/i, name: '로베르 에 루이즈', cat: 'eat', emoji: '🔥', mins: 70, cost: 35,
    blurb: '장작불 위에서 굽는 소갈비의 집. 나무 탁자, 검게 그을린 벽난로, 종이 식탁보. 둘이 가야 한 덩이를 시킬 수 있다.',
    dishes: [
      D('장작구이 소갈비 (2인)', 'Côte de bœuf', '벽난로에서 굽는다. 감자와 샐러드.', 60, 60, '🥩', ['savory', 'classic']),
      D('오리 콩피', 'Confit de canard', '', 22, 45, '🦆', ['savory', 'classic']),
      D('하우스 와인 한 병', 'Pichet', '', 14, 20, '🍷', ['drink', 'alcohol', 'classic']),
    ], menuNote: '대표 메뉴. 가격은 대략입니다.' },
  { match: /^Comme à Lisbonne$/i, name: '콤 아 리스본', cat: 'sweet', emoji: '🥧', mins: 8, cost: 3,
    blurb: '파스텔 드 나타 전문. 갓 구운 것은 겉이 그을려 있고 안이 흔들린다. 창구에서 사서 걸으며 먹는다.',
    dishes: [
      D('파스텔 드 나타', 'Pastel de nata', '계피를 뿌려 준다.', 2.5, 4, '🥧', ['sweet', 'classic', 'street']),
      D('비카 (에스프레소)', 'Bica', '', 2, 3, '☕', ['drink']),
    ] },
  { match: /^Une Glace à Paris$/i, name: '윈 글라스 아 파리', cat: 'sweet', emoji: '🍦', mins: 8, cost: 6,
    blurb: '프랑스 최우수 장인(MOF) 글라시에의 아이스크림 가게. 훈연 바닐라 같은 이상한 맛이 있다.',
    dishes: [
      D('두 스쿱', '2 boules', '훈연 바닐라를 권한다.', 6, 8, '🍦', ['sweet', 'street', 'trendy']),
      D('아이스크림 케이크 한 조각', 'Part de gâteau glacé', '', 8, 10, '🍰', ['sweet', 'trendy']),
    ] },
  { match: /^Amorino$/i, name: '아모리노', cat: 'sweet', emoji: '🌹', mins: 8, cost: 5,
    blurb: '젤라토를 장미 꽃잎 모양으로 쌓아 주는 이탈리아 체인. 관광지마다 있지만 그래도 맛있다.',
    dishes: [
      D('장미 젤라토 (콘)', 'Cornet', '맛은 원하는 만큼 섞어 준다.', 5.5, 8, '🌹', ['sweet', 'street']),
      D('마카롱 얹기', '+ macaron', '', 1, 0, '🧁', ['sweet']),
    ] },
  { match: /^Aleph$/i, name: '메종 알레프', cat: 'sweet', emoji: '🍯', mins: 8, cost: 5,
    blurb: '레반트(시리아·레바논)식 파티스리. 실처럼 가는 카다이프 반죽으로 만든 작은 둥지에 크림을 채운다.',
    dishes: [
      D('둥지 과자 세 개', 'Nids', '피스타치오·장미·타히니.', 9, 8, '🪺', ['sweet', 'trendy']),
      D('카다멈 커피', 'Café à la cardamome', '', 3, 5, '☕', ['drink']),
    ] },
  { match: /^Pain de Sucre$/i, name: '팽 드 쉬크르', cat: 'sweet', emoji: '🍬', mins: 8, cost: 6,
    blurb: '랑뷔토 거리의 파티스리. 색색의 마시멜로 막대와 정교한 타르트.',
    dishes: [
      D('마시멜로 막대', 'Guimauves', '장미·바이올렛·패션프루트.', 3, 3, '🍬', ['sweet', 'classic']),
      D('타르트 하나', 'Tartelette', '', 7, 8, '🥧', ['sweet', 'trendy']),
    ] },
  { match: /^Popelini$/i, name: '포플리니', cat: 'sweet', emoji: '🟠', mins: 6, cost: 4,
    blurb: '슈 하나에 한 가지 맛. 진열장에 색색의 슈만 줄지어 있다.',
    dishes: [
      D('슈 세 개', 'Choux', '캐러멜·피스타치오·오늘의 맛.', 7, 6, '🟠', ['sweet', 'trendy', 'street']),
    ] },
  { match: /^Grazie$/i, name: '그라치에', cat: 'eat', emoji: '🍕', mins: 50, cost: 18,
    blurb: '벽돌과 철제의 넓은 피자집. 나폴리식 화덕 피자와 칵테일.',
    dishes: [
      D('마르게리타', 'Margherita', '', 14, 35, '🍕', ['savory', 'classic']),
      D('부라타 피자', 'Burrata', '', 18, 35, '🧀', ['savory', 'trendy']),
      D('네그로니', 'Negroni', '', 11, 20, '🍹', ['drink', 'alcohol', 'trendy']),
    ] },
  { match: /Big Mamma/i, name: '비그러브 (빅 마마)', cat: 'bar', emoji: '💗', mins: 45, cost: 20,
    blurb: '빅 마마 그룹의 시끌벅적한 이탈리안. 예약 없이 줄 서서 들어간다. 커다란 부라타와 큰 소리의 음악.',
    dishes: [
      D('부라타', 'Burrata', '접시만 하다.', 15, 30, '🧀', ['savory', 'trendy']),
      D('파스타', 'Pasta', '', 16, 35, '🍝', ['savory', 'trendy']),
      D('스프리츠', 'Spritz', '', 9, 15, '🍹', ['drink', 'alcohol', 'trendy']),
    ] },
  { match: /^Manteigaria/i, name: '만테이가리아', cat: 'sweet', emoji: '🥧', mins: 8, cost: 3,
    blurb: '리스본에서 온 파스텔 드 나타 공장형 가게. 유리 너머로 만드는 걸 보며 기다린다. 종이 울리면 새 판이 나온 것.',
    dishes: [
      D('파스텔 드 나타', 'Pastel de nata', '나오자마자 먹는 게 정답.', 2, 4, '🥧', ['sweet', 'classic', 'street']),
      D('에스프레소', 'Café', '', 2, 3, '☕', ['drink']),
    ] },
  { match: /^Chez Alain Miam Miam$/i, name: '셰 알랭 미암미암', cat: 'eat', emoji: '🥪', mins: 30, cost: 12,
    blurb: '앙팡 루주 시장 안, 콧수염 아저씨가 즉석에서 만드는 거대한 샌드위치. 줄이 길고, 줄 서는 동안 치즈를 갈아 넣는 걸 구경한다.',
    dishes: [
      D('오늘의 샌드위치', 'Sandwich', '갓 구운 빵에 콩테 치즈를 산처럼.', 12, 25, '🥪', ['savory', 'street', 'trendy']),
      D('갈레트', 'Galette', '', 12, 25, '🥞', ['savory', 'street']),
    ] },
  { match: /^Le Progrès$/i, name: '르 프로그레', cat: 'cafe', emoji: '☕', mins: 30, cost: 7,
    blurb: '브르타뉴 거리 모퉁이의 동네 카페. 테라스에서 사람 구경하기 좋은 자리로 소문났다.',
    dishes: [
      D('카페 크렘', 'Café crème', '', 4.5, 20, '☕', ['drink', 'classic']),
      D('와인 한 잔', 'Verre de vin', '', 6, 25, '🍷', ['drink', 'alcohol']),
      D('크로크무슈', 'Croque-monsieur', '', 12, 25, '🥪', ['savory', 'classic']),
    ] },
  { match: /^La Cantine de Merci$/i, name: '메르시 캉틴', cat: 'cafe', emoji: '🍅', mins: 40, cost: 16,
    blurb: '편집숍 메르시(Merci) 안의 식당. 그날 시장에서 가져온 채소 위주의 한 접시. 안뜰의 빨간 피아트가 가게 상징.',
    dishes: [
      D('오늘의 한 접시', 'Assiette du jour', '채소·곡물·단백질 하나.', 16, 35, '🥗', ['savory', 'trendy']),
      D('수프', 'Soupe', '', 9, 20, '🥣', ['savory']),
      D('레모네이드', 'Citronnade', '', 5, 10, '🍋', ['drink']),
    ] },
  { match: /^Au Bouquet Saint-Paul$/i, name: '오 부케 생폴', cat: 'eat', emoji: '🍽️', mins: 50, cost: 22,
    blurb: '생폴 역 바로 앞, 리볼리 거리 모퉁이의 전형적인 파리 카페 브라스리. 테라스가 넓다. 특별하진 않지만 실패도 없다.',
    dishes: [
      D('크로크마담', 'Croque-madame', '달걀을 얹은 크로크무슈.', 13, 25, '🍳', ['savory', 'classic']),
      D('스테이크 프리트', 'Steak frites', '', 19, 40, '🥩', ['savory', 'classic']),
      D('니스풍 샐러드', 'Salade niçoise', '', 15, 30, '🥗', ['savory', 'classic']),
      D('생맥주', 'Demi', '', 5, 15, '🍺', ['drink', 'alcohol']),
    ] },
  { match: /^Le Saint-Paul$/i, name: '르 생폴 (카페)', cat: 'cafe', emoji: '☕', mins: 25, cost: 6,
    blurb: '역 앞 카페. 지하철에서 올라와 첫 커피를 마시는 곳.',
    dishes: [
      D('에스프레소', 'Café', '카운터에서 서서.', 2.5, 5, '☕', ['drink', 'classic']),
      D('카페 크렘', 'Crème', '', 5, 20, '🥛', ['drink', 'classic']),
      D('크루아상', 'Croissant', '', 2, 5, '🥐', ['sweet', 'classic']),
    ] },
  { match: /^Fontaine Sully$/i, name: '퐁텐 쉴리 (카페)', cat: 'cafe', emoji: '☕', mins: 25, cost: 6,
    blurb: '오텔 드 쉴리 건너편 모퉁이 카페. 생탕투안 거리를 오가는 사람들을 보며.',
    dishes: [
      D('카페 크렘', 'Crème', '', 4.5, 20, '☕', ['drink', 'classic']),
      D('타르틴', 'Tartine', '', 9, 20, '🍞', ['savory', 'classic']),
    ] },
  { match: /^La Cidrerie du Marais$/i, name: '라 시드르리 뒤 마레', cat: 'cafe', emoji: '🍏', mins: 35, cost: 14,
    blurb: '생폴 역 근처의 브르타뉴식 크레프리. 사기 사발에 따라 주는 시드르와 메밀 갈레트.',
    dishes: [
      D('갈레트 콩플레트', 'Galette complète', '햄·치즈·달걀.', 11, 30, '🥞', ['savory', 'classic']),
      D('버터 설탕 크레프', 'Crêpe beurre-sucre', '', 5, 12, '🧈', ['sweet', 'classic']),
      D('시드르 한 사발', 'Bolée de cidre', '', 4.5, 10, '🍏', ['drink', 'alcohol', 'classic']),
    ] },
  { match: /^Miss Manon$/i, name: '미스 마농 (빵집)', cat: 'bakery', emoji: '🥖', mins: 6, cost: 3,
    blurb: '생탕투안 거리의 빵집. 아침엔 크루아상 줄, 점심엔 샌드위치 줄.',
    dishes: [
      D('바게트 트라디시옹', 'Tradition', '', 1.5, 3, '🥖', ['savory', 'classic', 'street']),
      D('크루아상', 'Croissant', '', 1.6, 4, '🥐', ['sweet', 'classic', 'street']),
      D('잠봉뵈르', 'Jambon-beurre', '', 5.5, 10, '🥪', ['savory', 'classic', 'street']),
      D('플랑', 'Flan', '', 3.5, 6, '🍮', ['sweet', 'classic']),
    ] },
  { match: /^Aux Désirs de Manon$/i, name: '오 데지르 드 마농 (빵집)', cat: 'bakery', emoji: '🥐', mins: 6, cost: 3,
    blurb: '생폴 성당 근처 빵집. 아침 크루아상, 점심 샌드위치.',
    dishes: [
      D('크루아상', 'Croissant', '', 1.6, 4, '🥐', ['sweet', 'classic', 'street']),
      D('팽 오 쇼콜라', 'Pain au chocolat', '', 1.8, 4, '🍫', ['sweet', 'classic', 'street']),
      D('샌드위치', 'Sandwich', '', 6, 10, '🥪', ['savory', 'street']),
    ] },
  { match: /^Paul$/i, name: '폴 (Paul)', cat: 'bakery', emoji: '🥖', mins: 6, cost: 3,
    blurb: '프랑스 전역의 빵집 체인. 어디서나 같은 맛이라는 게 장점이자 단점.',
    dishes: [
      D('바게트', 'Baguette', '', 1.3, 3, '🥖', ['savory', 'classic', 'street']),
      D('크루아상', 'Croissant', '', 1.5, 4, '🥐', ['sweet', 'classic', 'street']),
      D('샌드위치', 'Sandwich', '', 6, 10, '🥪', ['savory', 'street']),
    ] },
  { match: /^Starbucks$/i, name: '스타벅스', cat: 'cafe', emoji: '🧜', mins: 15, cost: 5,
    blurb: '어디나 있는 그것. 파리 카페가 낯설 때의 비상구.',
    dishes: [
      D('라테', 'Latte', '', 5, 12, '☕', ['drink']),
      D('머핀', 'Muffin', '', 3.5, 5, '🧁', ['sweet']),
    ] },
  { match: /^Subway$/i, name: '서브웨이', cat: 'eat', emoji: '🥖', mins: 15, cost: 8,
    blurb: '어디나 있는 그것.',
    dishes: [D('샌드위치 15cm', 'Sub', '', 7, 12, '🥪', ['savory', 'street'])] },
  { match: /^L'Atelier du Chocolat$/i, name: '라틀리에 뒤 쇼콜라', cat: 'sweet', emoji: '🍫', mins: 8, cost: 6,
    blurb: '바욘(바스크)에서 온 쇼콜라티에. 얇은 초콜릿 조각을 부케처럼 담아 판다.',
    dishes: [
      D('초콜릿 부케', 'Bouquet de chocolat', '얇은 조각 여러 가지.', 8, 5, '💐', ['sweet', 'classic']),
      D('쇼콜라 쇼', 'Chocolat chaud', '', 5, 12, '☕', ['drink', 'sweet']),
    ] },
  { match: /^Les Trois Chocolats$/i, name: '레 트루아 쇼콜라', cat: 'sweet', emoji: '🍫', mins: 8, cost: 6,
    blurb: '일본인 쇼콜라티에의 작은 가게. 유자, 말차, 검은깨 같은 맛이 섞여 있다.',
    dishes: [
      D('봉봉 네 개', 'Bonbons', '유자·말차·검은깨·캐러멜.', 8, 5, '🍫', ['sweet', 'trendy']),
      D('말차 쇼콜라 쇼', 'Chocolat chaud matcha', '', 6, 12, '🍵', ['drink', 'sweet', 'trendy']),
    ] },
  { match: /^Beillevaire$/i, name: '베유베르 (치즈·버터)', cat: 'gourmet', emoji: '🧈', mins: 10, cost: 0,
    blurb: '낭트 근교 농장의 버터로 유명한 치즈 가게. 소금 결정이 씹히는 버터를 종이에 싸서 판다.',
    dishes: [
      D('소금 버터 한 덩이', 'Beurre demi-sel', '결정이 씹힌다. 바게트에.', 4, 3, '🧈', ['savory', 'classic']),
      D('치즈 한 조각', 'Fromage', '', 5, 5, '🧀', ['savory', 'classic']),
      D('구경만 한다', '', '', 0, 6, '👀', []),
    ] },
  { match: /^Nysa$/i, name: '니사 (와인)', cat: 'gourmet', emoji: '🍷', mins: 10, cost: 0,
    blurb: '파리 곳곳에 있는 와인 가게 체인. 15유로 안팎에서 고르기 좋다. 호텔에서 마실 한 병.',
    dishes: [
      D('오늘 추천 한 병', 'Bouteille', '점원에게 예산을 말하면 골라 준다.', 14, 6, '🍷', ['alcohol']),
      D('구경만 한다', '', '', 0, 6, '👀', []),
    ] },
  { match: /^Comtesse du Barry$/i, name: '콩테스 뒤 바리', cat: 'gourmet', emoji: '🦆', mins: 8, cost: 0,
    blurb: '남서부 푸아그라·통조림 전문. 선물용 작은 병들이 줄지어 있다.',
    dishes: [
      D('작은 파테 한 병', 'Terrine', '', 8, 4, '🫙', ['savory', 'classic']),
      D('구경만 한다', '', '', 0, 5, '👀', []),
    ] },
  { match: /^Famille Mary$/i, name: '파미유 마리 (꿀)', cat: 'gourmet', emoji: '🍯', mins: 8, cost: 0,
    blurb: '앙주 지방 양봉 가족의 꿀 가게. 시식 스푼을 준다.',
    dishes: [
      D('꿀 작은 병', 'Miel', '밤꿀이 진하다.', 7, 4, '🍯', ['sweet', 'classic']),
      D('시식만 한다', '', '', 0, 5, '🥄', []),
    ] },
  { match: /^Maison de thé$/i, name: '메종 드 테', cat: 'gourmet', emoji: '🍵', mins: 10, cost: 0,
    blurb: '찻잎 가게. 통마다 코를 대 본다.',
    dishes: [
      D('차 50g', 'Thé', '', 9, 6, '🍵', ['classic']),
      D('구경만 한다', '', '', 0, 6, '👃', []),
    ] },
  { match: /^Julien de Savignac$/i, name: '쥘리앵 드 사비냐크 (와인)', cat: 'gourmet', emoji: '🍷', mins: 10, cost: 0,
    blurb: '베르주라크 출신 가족의 와인 가게. 남서부 와인이 많다.',
    dishes: [
      D('남서부 와인 한 병', 'Bouteille', '', 15, 6, '🍷', ['alcohol', 'classic']),
      D('구경만 한다', '', '', 0, 6, '👀', []),
    ] },
  { match: /^Casa Treo$/i, name: '카사 트레오', cat: 'gourmet', emoji: '🫒', mins: 8, cost: 0,
    blurb: '이탈리아 식료품. 올리브유, 파스타, 치즈.',
    dishes: [
      D('올리브유 작은 병', 'Huile d\'olive', '', 12, 4, '🫒', ['classic']),
      D('구경만 한다', '', '', 0, 6, '👀', []),
    ] },
  { match: /^Apertivus$/i, name: '아페리티뷔스', cat: 'gourmet', emoji: '🧀', mins: 8, cost: 0,
    blurb: '아페리티프용 안주 가게. 소시송, 치즈, 올리브.',
    dishes: [
      D('소시송 하나', 'Saucisson', '', 8, 4, '🥓', ['savory', 'classic']),
      D('올리브 한 통', 'Olives', '', 5, 3, '🫒', ['savory']),
    ] },
  { match: /^Guzao$/i, name: '구자오', cat: 'sweet', emoji: '🥮', mins: 8, cost: 5,
    blurb: '아시아 풍 디저트 가게.',
    dishes: [D('오늘의 디저트', 'Dessert', '', 6, 8, '🥮', ['sweet', 'trendy'])] },
  { match: /^À Saint Paul$/i, name: '아 생폴 (아이스크림)', cat: 'sweet', emoji: '🍦', mins: 6, cost: 4,
    blurb: '역 앞 아이스크림 창구.',
    dishes: [D('아이스크림 두 스쿱', '2 boules', '', 5, 6, '🍦', ['sweet', 'street'])] },
  { match: /^Le Bûcheron$/i, name: '르 뷔슈롱', cat: 'eat', emoji: '🍽️', mins: 50, cost: 22,
    blurb: '"나무꾼". 리볼리 거리의 큰 브라스리. 늦게까지 열어 밤에 요긴하다.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 17, 40, '🍲', ['savory', 'classic']),
      D('타르타르', 'Tartare', '', 19, 40, '🥩', ['savory', 'classic']),
      D('생맥주', 'Demi', '', 5, 15, '🍺', ['drink', 'alcohol']),
    ] },
  { match: /^Le Bistrot Saint-Paul$/i, name: '르 비스트로 생폴', cat: 'cafe', emoji: '☕', mins: 30, cost: 8,
    blurb: '역 앞 모퉁이 카페.',
    dishes: [
      D('카페 크렘', 'Crème', '', 4.5, 20, '☕', ['drink', 'classic']),
      D('크로크무슈', 'Croque-monsieur', '', 12, 25, '🥪', ['savory', 'classic']),
    ] },
  { match: /^Les Chimères$/i, name: '레 시메르', cat: 'cafe', emoji: '☕', mins: 30, cost: 8,
    blurb: '생탕투안 거리의 카페. 테라스.',
    dishes: [
      D('카페 크렘', 'Crème', '', 4.5, 20, '☕', ['drink', 'classic']),
      D('타르틴', 'Tartine', '', 9, 20, '🍞', ['savory', 'classic']),
    ] },
  { match: /^Khao Thai$/i, name: '카오 타이', cat: 'eat', emoji: '🍛', mins: 45, cost: 18,
    blurb: '태국 음식점.',
    dishes: [
      D('팟타이', 'Pad thaï', '', 14, 30, '🍜', ['savory', 'classic']),
      D('그린 커리', 'Curry vert', '', 15, 35, '🍛', ['savory', 'classic']),
      D('타이 아이스티', 'Thé glacé', '', 4, 5, '🧋', ['drink']),
    ] },
  { match: /^Au Petit Thaï$/i, name: '오 프티 타이', cat: 'eat', emoji: '🍛', mins: 45, cost: 17,
    blurb: '태국 음식점.',
    dishes: [
      D('팟타이', 'Pad thaï', '', 13, 30, '🍜', ['savory', 'classic']),
      D('똠얌꿍', 'Tom yum', '', 12, 25, '🍲', ['savory', 'classic']),
    ] },
  { match: /^Chez Ajia$/i, name: '셰 아지아', cat: 'eat', emoji: '🥟', mins: 40, cost: 16,
    blurb: '대만식 가정 음식.',
    dishes: [
      D('루로판 (돼지고기 덮밥)', 'Lu rou fan', '', 13, 30, '🍚', ['savory', 'classic']),
      D('만두', 'Raviolis', '', 9, 20, '🥟', ['savory', 'classic']),
      D('버블티', 'Bubble tea', '', 5, 10, '🧋', ['drink', 'trendy']),
    ] },
  { match: /^Keko Momo$/i, name: '케코 모모', cat: 'eat', emoji: '🍜', mins: 40, cost: 15,
    blurb: '산시(陕西)식 손국수와 만두.',
    dishes: [
      D('손국수 (비앙비앙)', 'Nouilles biang biang', '넓적한 면에 고추기름.', 13, 30, '🍜', ['savory', 'classic']),
      D('만두', 'Momo', '', 9, 20, '🥟', ['savory', 'classic']),
    ] },
  { match: /^Imperial House$/i, name: '임페리얼 하우스', cat: 'eat', emoji: '🥢', mins: 45, cost: 18,
    blurb: '중국 음식점.',
    dishes: [
      D('오늘의 정식', 'Menu du jour', '', 14, 35, '🍱', ['savory']),
      D('딤섬 한 판', 'Dim sum', '', 9, 20, '🥟', ['savory', 'classic']),
    ] },
  { match: /^Casa San Pablo$/i, name: '카사 산 파블로', cat: 'eat', emoji: '🥘', mins: 50, cost: 22,
    blurb: '스페인 타파스 바.',
    dishes: [
      D('타파스 세 가지', 'Tapas', '하몽·감자 브라바스·오징어.', 18, 40, '🥘', ['savory', 'classic']),
      D('상그리아 한 잔', 'Sangria', '', 7, 15, '🍹', ['drink', 'alcohol']),
    ] },
  { match: /^Mangerie$/i, name: '망주리', cat: 'eat', emoji: '🥘', mins: 45, cost: 20,
    blurb: '스페인 음식점.',
    dishes: [
      D('타파스 세 가지', 'Tapas', '', 17, 40, '🥘', ['savory', 'classic']),
      D('리오하 한 잔', 'Rioja', '', 6, 15, '🍷', ['drink', 'alcohol']),
    ] },
  { match: /^Pizza Momo$/i, name: '피자 모모', cat: 'eat', emoji: '🍕', mins: 30, cost: 12,
    blurb: '역 앞 피자.',
    dishes: [
      D('마르게리타', 'Margherita', '', 11, 25, '🍕', ['savory', 'classic']),
      D('조각 피자', 'Part', '들고 걷는다.', 4, 8, '🍕', ['savory', 'street']),
    ] },
  { match: /^Ciore$/i, name: '초레', cat: 'eat', emoji: '🍝', mins: 45, cost: 20,
    blurb: '이탈리아 음식점.',
    dishes: [
      D('오늘의 파스타', 'Pâtes du jour', '', 16, 35, '🍝', ['savory']),
      D('티라미수', 'Tiramisu', '', 8, 10, '🍰', ['sweet', 'classic']),
    ] },
  { match: /^Kura-Ge$/i, name: '쿠라게', cat: 'eat', emoji: '🍙', mins: 20, cost: 10,
    blurb: '일본식 간편식.',
    dishes: [
      D('벤토', 'Bento', '', 12, 20, '🍱', ['savory']),
      D('오니기리 두 개', 'Onigiri', '', 6, 8, '🍙', ['savory', 'street']),
    ] },
  { match: /^Poke House$/i, name: '포케 하우스', cat: 'eat', emoji: '🥗', mins: 20, cost: 13,
    blurb: '포케 볼.',
    dishes: [D('포케 볼', 'Poke bowl', '', 13, 20, '🥗', ['savory', 'trendy'])] },
  { match: /^Wrap Stories$/i, name: '랩 스토리즈', cat: 'eat', emoji: '🌯', mins: 15, cost: 10,
    blurb: '랩 샌드위치.',
    dishes: [D('랩', 'Wrap', '', 10, 15, '🌯', ['savory', 'street', 'trendy'])] },
  { match: /^Clark hot dog/i, name: '클라크 (핫도그·커피)', cat: 'eat', emoji: '🌭', mins: 15, cost: 8,
    blurb: '핫도그와 커피.',
    dishes: [
      D('핫도그', 'Hot dog', '', 7, 10, '🌭', ['savory', 'street']),
      D('커피', 'Café', '', 3, 5, '☕', ['drink']),
    ] },
  { match: /^Crêperie de Turenne$/i, name: '크레프리 드 튀렌', cat: 'eat', emoji: '🥞', mins: 15, cost: 7,
    blurb: '창구에서 파는 크레프와 케밥. 들고 걷는다.',
    dishes: [
      D('누텔라 크레프', 'Crêpe Nutella', '', 5, 8, '🥞', ['sweet', 'street']),
      D('케밥 샌드위치', 'Kebab', '', 8, 12, '🥙', ['savory', 'street']),
    ] },
  { match: /^Bubble Tea Snacks$/i, name: '버블티 스낵', cat: 'cafe', emoji: '🧋', mins: 10, cost: 6,
    blurb: '버블티 창구.',
    dishes: [D('버블티', 'Bubble tea', '', 6, 8, '🧋', ['drink', 'trendy', 'street'])] },
  { match: /^Méo$/i, name: '메오 (커피)', cat: 'cafe', emoji: '☕', mins: 15, cost: 4,
    blurb: '릴 출신 커피 로스터의 카페. 원두를 판다.',
    dishes: [
      D('에스프레소', 'Espresso', '', 2.5, 5, '☕', ['drink']),
      D('플랫 화이트', 'Flat white', '', 5, 12, '🥛', ['drink', 'trendy']),
    ] },
  { match: /^City of Light\.?$/i, name: '시티 오브 라이트', cat: 'cafe', emoji: '☕', mins: 20, cost: 6,
    blurb: '작은 커피숍.',
    dishes: [
      D('플랫 화이트', 'Flat white', '', 5, 12, '🥛', ['drink', 'trendy']),
      D('바나나 브레드', 'Banana bread', '', 4, 6, '🍌', ['sweet', 'trendy']),
    ] },
  { match: /^Joji$/i, name: '조지', cat: 'cafe', emoji: '☕', mins: 20, cost: 6,
    blurb: '작은 카페.',
    dishes: [
      D('라테', 'Latte', '', 5, 12, '☕', ['drink', 'trendy']),
      D('쿠키', 'Cookie', '', 3.5, 5, '🍪', ['sweet', 'trendy']),
    ] },
  { match: /^Le Rivolux$/i, name: '르 리볼뤽스', cat: 'cafe', emoji: '☕', mins: 25, cost: 6,
    blurb: '리볼리 거리의 카페.',
    dishes: [
      D('카페 크렘', 'Crème', '', 4.5, 20, '☕', ['drink', 'classic']),
      D('생맥주', 'Demi', '', 5, 15, '🍺', ['drink', 'alcohol']),
    ] },
  { match: /^La Favorite$/i, name: '라 파보리트', cat: 'bar', emoji: '🍸', mins: 35, cost: 10,
    blurb: '생폴 역 코앞의 큰 카페 바. 아침부터 밤까지 열려 있고 테라스가 리볼리 거리로 향한다. 동네 사람과 관광객이 반반.',
    dishes: [
      D('생맥주', 'Demi', '', 5.5, 20, '🍺', ['drink', 'alcohol']),
      D('칵테일', 'Cocktail', '', 11, 25, '🍸', ['drink', 'alcohol', 'trendy']),
      D('카페 크렘', 'Crème', '', 4.5, 15, '☕', ['drink', 'classic']),
      D('버거', 'Burger', '', 16, 35, '🍔', ['savory']),
    ] },
  { match: /^JOBO$/i, name: '조보', cat: 'bar', emoji: '🍸', mins: 40, cost: 14,
    blurb: '호텔 안의 바.',
    dishes: [
      D('칵테일', 'Cocktail', '', 14, 25, '🍸', ['drink', 'alcohol', 'trendy']),
      D('와인 한 잔', 'Verre de vin', '', 8, 25, '🍷', ['drink', 'alcohol']),
    ] },
  { match: /^The Pub$/i, name: '더 펍', cat: 'bar', emoji: '🍺', mins: 40, cost: 8,
    blurb: '영국식 펍.',
    dishes: [
      D('파인트', 'Pinte', '', 8, 25, '🍺', ['drink', 'alcohol', 'classic']),
      D('피시 앤 칩스', 'Fish & chips', '', 16, 35, '🐟', ['savory', 'classic']),
    ] },
  { match: /^The Auld Alliance$/i, name: '디 올드 얼라이언스', cat: 'bar', emoji: '🥃', mins: 40, cost: 9,
    blurb: '스코틀랜드 펍. 위스키 종류가 많고, 럭비 경기 날엔 꽉 찬다.',
    dishes: [
      D('위스키 한 잔', 'Whisky', '', 9, 20, '🥃', ['drink', 'alcohol', 'classic']),
      D('파인트', 'Pinte', '', 8, 25, '🍺', ['drink', 'alcohol']),
    ] },
  { match: /^Le Piment Café$/i, name: '르 피망 카페', cat: 'bar', emoji: '🌶️', mins: 40, cost: 9,
    blurb: '동네 바.',
    dishes: [
      D('칵테일', 'Cocktail', '', 10, 25, '🍹', ['drink', 'alcohol']),
      D('생맥주', 'Demi', '', 5, 20, '🍺', ['drink', 'alcohol']),
    ] },
  { match: /^Le Bistrot de la Place$/i, name: '르 비스트로 드 라 플라스', cat: 'bar', emoji: '🍷', mins: 45, cost: 18,
    blurb: '마르셰 생트카트린 광장의 카페. 광장 테라스가 여름 저녁에 좋다.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 17, 40, '🍲', ['savory', 'classic']),
      D('와인 한 잔', 'Verre de vin', '', 6, 25, '🍷', ['drink', 'alcohol', 'classic']),
      D('샤퀴트리 플레이트', 'Planche', '', 15, 35, '🥓', ['savory', 'classic']),
    ] },
  { match: /^Chez Joséphine$/i, name: '셰 조제핀', cat: 'eat', emoji: '🍽️', mins: 60, cost: 26,
    blurb: '프랑스 가정식 비스트로.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 19, 45, '🍲', ['savory', 'classic']),
      D('크렘 브륄레', 'Crème brûlée', '', 8, 12, '🍮', ['sweet', 'classic']),
    ] },
  { match: /^Chez Mademoiselle$/i, name: '셰 마드무아젤', cat: 'eat', emoji: '🍽️', mins: 60, cost: 26,
    blurb: '프랑스 음식 비스트로.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 19, 45, '🍲', ['savory', 'classic']),
      D('타르트 타탱', 'Tarte Tatin', '', 8, 12, '🥧', ['sweet', 'classic']),
    ] },
  { match: /^Le Marché$/i, name: '르 마르셰', cat: 'eat', emoji: '🍽️', mins: 60, cost: 26,
    blurb: '마르셰 생트카트린 광장의 비스트로. 광장 테라스.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 19, 45, '🍲', ['savory', 'classic']),
      D('와인 한 잔', 'Verre de vin', '', 6, 20, '🍷', ['drink', 'alcohol']),
    ] },
  { match: /^Le potager du Marais$/i, name: '르 포타제 뒤 마레', cat: 'eat', emoji: '🥕', mins: 55, cost: 24,
    blurb: '오래된 채식 비스트로. 좁고 긴 가게에 어깨를 붙이고 앉는다.',
    dishes: [
      D('채소 그라탱', 'Gratin', '', 18, 40, '🥘', ['savory']),
      D('오늘의 수프', 'Soupe', '', 9, 20, '🥣', ['savory']),
      D('초콜릿 케이크', 'Gâteau au chocolat', '', 8, 12, '🍫', ['sweet']),
    ] },
  { match: /^Nostre$/i, name: '노스트르', cat: 'eat', emoji: '🍽️', mins: 60, cost: 28,
    blurb: '프랑스 음식점.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 21, 45, '🍲', ['savory', 'classic']),
      D('와인 한 잔', 'Verre de vin', '', 7, 20, '🍷', ['drink', 'alcohol']),
    ] },
  { match: /^L'Éléphant du Nil$/i, name: '렐레팡 뒤 닐', cat: 'eat', emoji: '🐘', mins: 50, cost: 22,
    blurb: '프랑스 음식점.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 18, 40, '🍲', ['savory', 'classic']),
      D('크렘 브륄레', 'Crème brûlée', '', 8, 12, '🍮', ['sweet', 'classic']),
    ] },
  { match: /^Les Petites Bouchées$/i, name: '레 프티트 부셰', cat: 'eat', emoji: '🍔', mins: 40, cost: 18,
    blurb: '타파스와 버거.',
    dishes: [
      D('버거', 'Burger', '', 15, 30, '🍔', ['savory', 'trendy']),
      D('타파스 세 가지', 'Tapas', '', 14, 30, '🥘', ['savory']),
    ] },
  { match: /^Le Seafood$/i, name: '르 시푸드', cat: 'eat', emoji: '🦐', mins: 55, cost: 30,
    blurb: '해산물 전문.',
    dishes: [
      D('해산물 모둠', 'Plateau', '', 32, 50, '🦐', ['savory', 'classic']),
      D('홍합과 감자튀김', 'Moules-frites', '', 18, 35, '🦪', ['savory', 'classic']),
    ] },
  { match: /^Salento Marais$/i, name: '살렌토 마레', cat: 'eat', emoji: '🍝', mins: 45, cost: 20,
    blurb: '풀리아(이탈리아 남부) 음식.',
    dishes: [
      D('오레키에테', 'Orecchiette', '귀 모양 파스타에 순무잎.', 16, 35, '🍝', ['savory', 'classic']),
      D('포카치아', 'Focaccia', '', 6, 10, '🫓', ['savory', 'street']),
    ] },
  { match: /^A Modo Mio$/i, name: '아 모도 미오', cat: 'eat', emoji: '🍝', mins: 45, cost: 20,
    blurb: '이탈리아 음식점.',
    dishes: [
      D('오늘의 파스타', 'Pâtes', '', 16, 35, '🍝', ['savory']),
      D('티라미수', 'Tiramisu', '', 8, 10, '🍰', ['sweet', 'classic']),
    ] },
  { match: /^Pinot Grigio$/i, name: '피노 그리조', cat: 'eat', emoji: '🍕', mins: 45, cost: 18,
    blurb: '이탈리아 음식점. 피자와 파스타.',
    dishes: [
      D('마르게리타', 'Margherita', '', 13, 35, '🍕', ['savory', 'classic']),
      D('오늘의 파스타', 'Pâtes', '', 15, 35, '🍝', ['savory']),
    ] },
  { match: /^La Cerise sur la pizza$/i, name: '라 스리즈 쉬르 라 피자', cat: 'eat', emoji: '🍕', mins: 40, cost: 16,
    blurb: '"피자 위의 체리". 피자집.',
    dishes: [
      D('마르게리타', 'Margherita', '', 13, 30, '🍕', ['savory', 'classic']),
      D('오늘의 피자', 'Pizza du jour', '', 16, 30, '🍕', ['savory', 'trendy']),
    ] },
  { match: /^Bloom Sushi Marais$/i, name: '블룸 스시', cat: 'eat', emoji: '🍣', mins: 40, cost: 20,
    blurb: '스시.',
    dishes: [
      D('스시 모둠', 'Assortiment', '', 19, 35, '🍣', ['savory']),
      D('연어 롤', 'Roll saumon', '', 12, 25, '🍣', ['savory', 'trendy']),
    ] },
  { match: /^Sushi Wasabi$/i, name: '스시 와사비', cat: 'eat', emoji: '🍣', mins: 40, cost: 18,
    blurb: '스시.',
    dishes: [D('스시 모둠', 'Assortiment', '', 18, 35, '🍣', ['savory'])] },
  { match: /^Shinjuku Sushi$/i, name: '신주쿠 스시', cat: 'eat', emoji: '🍣', mins: 40, cost: 18,
    blurb: '일본 음식점.',
    dishes: [
      D('스시 모둠', 'Assortiment', '', 18, 35, '🍣', ['savory']),
      D('라멘', 'Ramen', '', 14, 30, '🍜', ['savory']),
    ] },
  { match: /^Delice House$/i, name: '델리스 하우스', cat: 'eat', emoji: '🥢', mins: 40, cost: 15,
    blurb: '중국 음식점.',
    dishes: [D('오늘의 정식', 'Menu', '', 13, 35, '🍱', ['savory'])] },
  { match: /^Aux Délices d'Asie$/i, name: '오 델리스 다지', cat: 'eat', emoji: '🥢', mins: 30, cost: 12,
    blurb: '아시아 음식 포장 판매.',
    dishes: [D('덮밥 도시락', 'Plat', '', 11, 20, '🍱', ['savory', 'street'])] },
  { match: /^Le Chinois Gourmet$/i, name: '르 시누아 구르메', cat: 'eat', emoji: '🥢', mins: 40, cost: 15,
    blurb: '역 앞 중국 음식점.',
    dishes: [D('오늘의 정식', 'Menu', '', 13, 35, '🍱', ['savory'])] },
  { match: /^BIA too$/i, name: 'BIA 투', cat: 'eat', emoji: '🥞', mins: 35, cost: 14,
    blurb: '브렉퍼스트 인 아메리카의 별관.',
    dishes: [
      D('팬케이크', 'Pancakes', '', 10, 25, '🥞', ['sweet', 'classic']),
      D('버거', 'Burger', '', 15, 30, '🍔', ['savory', 'classic']),
    ] },
  { match: /^Mezz'amour$/i, name: '메자무르', cat: 'eat', emoji: '🍽️', mins: 50, cost: 24,
    blurb: '음식점.',
    dishes: [D('오늘의 요리', 'Plat du jour', '', 18, 40, '🍲', ['savory'])] },
  { match: /^L'Être Ange$/i, name: '레트르 앙주', cat: 'eat', emoji: '🍽️', mins: 50, cost: 24,
    blurb: '음식점.',
    dishes: [D('오늘의 요리', 'Plat du jour', '', 18, 40, '🍲', ['savory'])] },
  { match: /^Chouette$/i, name: '슈에트', cat: 'eat', emoji: '🦉', mins: 50, cost: 24,
    blurb: '"부엉이". 음식점.',
    dishes: [D('오늘의 요리', 'Plat du jour', '', 18, 40, '🍲', ['savory'])] },
  { match: /^Les Rosiers$/i, name: '레 로지에', cat: 'eat', emoji: '🍽️', mins: 50, cost: 22,
    blurb: '음식점.',
    dishes: [D('오늘의 요리', 'Plat du jour', '', 17, 40, '🍲', ['savory'])] },
  { match: /^Les Gamins$/i, name: '레 가맹', cat: 'eat', emoji: '🍽️', mins: 50, cost: 22,
    blurb: '"꼬맹이들". 비스트로.',
    dishes: [D('오늘의 요리', 'Plat du jour', '', 17, 40, '🍲', ['savory', 'classic'])] },
  { match: /^Les Bougresses$/i, name: '레 부그레스', cat: 'eat', emoji: '🍽️', mins: 55, cost: 26,
    blurb: '프랑스 음식 비스트로.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 19, 45, '🍲', ['savory', 'classic']),
      D('치즈 플레이트', 'Fromages', '', 10, 15, '🧀', ['savory', 'classic']),
    ] },
  { match: /^Kébi$/i, name: '케비', cat: 'eat', emoji: '🥙', mins: 20, cost: 10,
    blurb: '케밥.',
    dishes: [D('케밥 샌드위치', 'Kebab', '', 9, 15, '🥙', ['savory', 'street'])] },
  { match: /^Hello You$/i, name: '헬로 유', cat: 'eat', emoji: '🥪', mins: 15, cost: 8,
    blurb: '샌드위치 창구.',
    dishes: [D('샌드위치', 'Sandwich', '', 7, 12, '🥪', ['savory', 'street'])] },
  { match: /^Pasta Linea$/i, name: '파스타 리네아', cat: 'eat', emoji: '🍝', mins: 20, cost: 11,
    blurb: '포장 파스타.',
    dishes: [D('파스타 한 통', 'Pâtes', '', 10, 15, '🍝', ['savory', 'street'])] },
  { match: /^BDJ$/i, name: 'BDJ', cat: 'eat', emoji: '🍽️', mins: 40, cost: 18,
    blurb: '음식점.',
    dishes: [D('오늘의 요리', 'Plat du jour', '', 16, 35, '🍲', ['savory'])] },
  { match: /^Land&Monkeys/i, name: '랜드 앤 몽키스', cat: 'bakery', emoji: '🌱', mins: 10, cost: 5,
    blurb: '비건 빵집·카페 체인. 크루아상도 버터 없이 만든다.',
    dishes: [
      D('비건 크루아상', 'Croissant vegan', '', 2.5, 5, '🥐', ['sweet', 'trendy']),
      D('샌드위치', 'Sandwich', '', 8, 12, '🥪', ['savory', 'trendy']),
      D('플랫 화이트 (귀리)', 'Flat white avoine', '', 5, 10, '🥛', ['drink', 'trendy']),
    ] },
  { match: /^M\. Jacques$/i, name: '므시외 자크 (빵집)', cat: 'bakery', emoji: '🥖', mins: 6, cost: 3,
    blurb: '동네 빵집.',
    dishes: [
      D('바게트', 'Baguette', '', 1.4, 3, '🥖', ['savory', 'classic', 'street']),
      D('크루아상', 'Croissant', '', 1.5, 4, '🥐', ['sweet', 'classic', 'street']),
    ] },
  { match: /^Ricola$/i, name: '리콜라', cat: 'sweet', emoji: '🍬', mins: 5, cost: 3,
    blurb: '스위스 허브 사탕 가게.',
    dishes: [D('사탕 한 봉지', 'Bonbons', '', 4, 3, '🍬', ['sweet'])] },
  { match: /^Benoit chocolats$/i, name: '브누아 쇼콜라', cat: 'sweet', emoji: '🍫', mins: 8, cost: 6,
    blurb: '쇼콜라티에.',
    dishes: [D('봉봉 네 개', 'Bonbons', '', 8, 5, '🍫', ['sweet', 'classic'])] },
  { match: /^Đoòng Café/i, name: '동 카페', cat: 'cafe', emoji: '🇻🇳', mins: 20, cost: 6,
    blurb: '베트남식 커피.',
    dishes: [
      D('연유 커피', 'Cà phê sữa đá', '', 5, 10, '🧊', ['drink', 'classic']),
      D('반미', 'Bánh mì', '', 8, 15, '🥖', ['savory', 'street']),
    ] },
  { match: /^L'Arsenal$/i, name: '라르스날 (카페)', cat: 'cafe', emoji: '☕', mins: 25, cost: 6,
    blurb: '카페.',
    dishes: [D('카페 크렘', 'Crème', '', 4.5, 20, '☕', ['drink', 'classic'])] },
  { match: /^Le Réveil Bastille$/i, name: '르 레베유 바스티유', cat: 'cafe', emoji: '☕', mins: 25, cost: 6,
    blurb: '바스티유 쪽 카페.',
    dishes: [D('카페 크렘', 'Crème', '', 4.5, 20, '☕', ['drink', 'classic'])] },
  { match: /^Le Petit Marché$/i, name: '르 프티 마르셰', cat: 'eat', emoji: '🍽️', mins: 55, cost: 26,
    blurb: '보주 광장 뒤편의 비스트로.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 19, 45, '🍲', ['savory', 'classic']),
      D('와인 한 잔', 'Verre de vin', '', 7, 20, '🍷', ['drink', 'alcohol']),
    ] },
  { match: /^Bar du Marché des Blancs Manteaux$/i, name: '바 뒤 마르셰 데 블랑 망토', cat: 'eat', emoji: '🍽️', mins: 50, cost: 22,
    blurb: '블랑 망토 시장 앞의 카페 식당. 지방 요리.',
    dishes: [
      D('오늘의 요리', 'Plat du jour', '', 17, 40, '🍲', ['savory', 'classic']),
      D('와인 한 잔', 'Verre de vin', '', 6, 20, '🍷', ['drink', 'alcohol']),
    ] },
  { match: /^Bistrot des Vosges$/i, name: '비스트로 데 보주', cat: 'eat', emoji: '🍽️', mins: 55, cost: 26,
    blurb: '보주 광장 근처의 비스트로.',
    dishes: [D('오늘의 요리', 'Plat du jour', '', 19, 45, '🍲', ['savory', 'classic'])] },
  { match: /^Le Relais de l'Hôtel de Ville$/i, name: '르 를레 드 로텔 드 빌', cat: 'cafe', emoji: '☕', mins: 30, cost: 8,
    blurb: '시청 근처 카페.',
    dishes: [
      D('카페 크렘', 'Crème', '', 4.5, 20, '☕', ['drink', 'classic']),
      D('크로크무슈', 'Croque-monsieur', '', 12, 25, '🥪', ['savory', 'classic']),
    ] },
];
